export const DEPARTMENT_CODES_STARTING = 'DEP';

export const SUBDEPARTMENT_CODES_STARTINGS = {
  MEATS: 'FRE',
  PRODUCE: 'PRO',
  BAKERY: 'BAK',
  DIARY_FROZEN: 'DIA',
};

export const STOCK_ALERT_TAKE = 8;
